//! Shared identifier strategy for DohFlow (plan §9.1.2, ADR 0013).
//!
//! Every entity identity in the workspace is a UUIDv7 newtype generated by the
//! [`uuid_id!`] macro. UUIDv7 is time-ordered, globally unique, and opaque; only
//! the typed wrapper is exposed, never raw bytes outside the controlled
//! accessors.
//!
//! Three properties this crate guarantees:
//! - **Monotonic creation order.** [`monotonic_v7`] uses a process-global
//!   `ContextV7`, so IDs created in sequence are strictly increasing even within
//!   one millisecond — `ORDER BY id` matches creation order.
//! - **Compact storage.** [`as_bytes`](crate#method.as_bytes) yields the 16-byte
//!   form db-worker stores as a SQLite `BLOB`. On the wire IDs stay
//!   `#[serde(transparent)]` UUID strings, so the IPC contract is human-readable.
//! - **Friendly display.** [`display_id`](crate#method.display_id) renders the
//!   128 bits as 26-char Crockford base32 (no ambiguous `I/L/O/U`,
//!   case-insensitive, round-trippable) for user-facing reference codes.
//!
//! The macro lives here, not in `core-ledger`, so every schema crate
//! (categories, forecast, income, …) shares one ID foundation without depending
//! on the ledger.

use std::sync::{Mutex, OnceLock};

use uuid::{ContextV7, Timestamp, Uuid};

/// Crockford base32 alphabet — excludes `I`, `L`, `O`, `U` to avoid ambiguity.
const CROCKFORD: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// Generate a new monotonic, time-ordered UUIDv7.
///
/// Backed by a process-global `ContextV7` (within-millisecond counter) plus the
/// last-issued value, behind a `Mutex`. The new id is **clamped to be strictly
/// greater than the previous one**, so a backward system-clock step (which
/// virtualized CI clocks do) or a within-millisecond counter wrap can never
/// produce a smaller id — `ORDER BY id` always reproduces creation order. The
/// clamp only engages on those rare edges; normal generation returns the plain
/// `ContextV7` value.
#[must_use]
pub fn monotonic_v7() -> Uuid {
    static STATE: OnceLock<Mutex<MonotonicState>> = OnceLock::new();
    let state = STATE.get_or_init(|| {
        Mutex::new(MonotonicState {
            ctx: ContextV7::new(),
            last: 0,
        })
    });
    let mut guard = state.lock().expect("id-generation context mutex poisoned");
    let candidate = Uuid::new_v7(Timestamp::now(&guard.ctx)).as_u128();
    let next = candidate.max(guard.last.wrapping_add(1));
    guard.last = next;
    Uuid::from_u128(next)
}

/// State backing [`monotonic_v7`]: the v7 clock-sequence context plus the last
/// id issued (as `u128`), so generation stays strictly increasing across clock
/// steps and counter wraps.
struct MonotonicState {
    ctx: ContextV7,
    last: u128,
}

/// Errors converting an identifier from bytes or a display string.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum IdError {
    /// The byte slice was not exactly 16 bytes.
    #[error("invalid id: expected 16 bytes")]
    BadLength,
    /// The display string was not a valid 26-char Crockford base32 id.
    #[error("invalid display id")]
    BadDisplayId,
}

/// Encode 16 bytes as a 26-character uppercase Crockford base32 string.
#[must_use]
pub fn encode_crockford(bytes: &[u8; 16]) -> String {
    let mut out = String::with_capacity(26);
    let mut buffer: u32 = 0;
    let mut bits: u32 = 0;
    for &byte in bytes {
        buffer = (buffer << 8) | u32::from(byte);
        bits += 8;
        while bits >= 5 {
            bits -= 5;
            out.push(CROCKFORD[((buffer >> bits) & 0x1f) as usize] as char);
        }
    }
    if bits > 0 {
        // 128 bits leaves 3 trailing bits; pad them up to a final symbol.
        out.push(CROCKFORD[((buffer << (5 - bits)) & 0x1f) as usize] as char);
    }
    out
}

/// Decode a 26-character Crockford base32 string back into 16 bytes.
///
/// Case-insensitive; treats `O`→`0` and `I`/`L`→`1` per Crockford's
/// ambiguity rules.
///
/// # Errors
/// Returns [`IdError::BadDisplayId`] if the string contains a non-alphabet
/// character or does not decode to exactly 16 bytes.
pub fn decode_crockford(s: &str) -> Result<[u8; 16], IdError> {
    let mut buffer: u32 = 0;
    let mut bits: u32 = 0;
    let mut out = Vec::with_capacity(16);
    for c in s.chars() {
        buffer = (buffer << 5) | u32::from(decode_char(c)?);
        bits += 5;
        if bits >= 8 {
            bits -= 8;
            out.push((buffer >> bits) as u8);
        }
    }
    let bytes: [u8; 16] = out.try_into().map_err(|_| IdError::BadDisplayId)?;
    Ok(bytes)
}

fn decode_char(c: char) -> Result<u8, IdError> {
    let normalized = match c.to_ascii_uppercase() {
        'O' => '0',
        'I' | 'L' => '1',
        other => other,
    };
    CROCKFORD
        .iter()
        .position(|&x| x as char == normalized)
        .map(|p| p as u8)
        .ok_or(IdError::BadDisplayId)
}

/// Define a UUIDv7-backed identifier newtype.
///
/// The generated type is monotonic-by-creation (via [`monotonic_v7`]),
/// `#[serde(transparent)]` (serializes as a UUID string for IPC), and exposes a
/// 16-byte form for compact storage plus a Crockford display id.
///
/// ```
/// core_ids::uuid_id! {
///     /// Example identity.
///     ExampleId
/// }
/// let id = ExampleId::new();
/// assert_eq!(ExampleId::from_display_id(&id.display_id()).unwrap(), id);
/// ```
#[macro_export]
macro_rules! uuid_id {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord,
            ::serde::Serialize, ::serde::Deserialize,
        )]
        #[serde(transparent)]
        pub struct $name(::uuid::Uuid);

        impl $name {
            #[doc = concat!("Generate a new monotonic, time-ordered `", stringify!($name), "` (UUIDv7).")]
            #[must_use]
            pub fn new() -> Self {
                Self($crate::monotonic_v7())
            }

            /// Wrap an existing UUID (e.g. when rehydrating from storage).
            #[must_use]
            pub const fn from_uuid(uuid: ::uuid::Uuid) -> Self {
                Self(uuid)
            }

            /// The underlying UUID.
            #[must_use]
            pub const fn as_uuid(self) -> ::uuid::Uuid {
                self.0
            }

            /// The compact 16-byte form (what db-worker stores as a SQLite BLOB).
            #[must_use]
            pub fn as_bytes(self) -> [u8; 16] {
                *self.0.as_bytes()
            }

            /// Rebuild from a 16-byte slice.
            ///
            /// # Errors
            /// Returns [`core_ids::IdError::BadLength`] if `bytes` is not 16 bytes.
            pub fn from_bytes(bytes: &[u8]) -> ::core::result::Result<Self, $crate::IdError> {
                ::uuid::Uuid::from_slice(bytes)
                    .map(Self)
                    .map_err(|_| $crate::IdError::BadLength)
            }

            /// A short, copy-safe display code (26-char Crockford base32),
            /// round-trippable via [`from_display_id`](Self::from_display_id).
            #[must_use]
            pub fn display_id(self) -> ::std::string::String {
                $crate::encode_crockford(self.0.as_bytes())
            }

            /// Parse a [`display_id`](Self::display_id) back into the typed id.
            ///
            /// # Errors
            /// Returns [`core_ids::IdError::BadDisplayId`] if `s` is not a valid
            /// 26-char Crockford id.
            pub fn from_display_id(s: &str) -> ::core::result::Result<Self, $crate::IdError> {
                $crate::decode_crockford(s).map(|bytes| Self(::uuid::Uuid::from_bytes(bytes)))
            }
        }

        impl ::core::default::Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl ::core::fmt::Display for $name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                ::core::fmt::Display::fmt(&self.0, f)
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crockford_round_trips_all_bytes() {
        let bytes: [u8; 16] = [
            0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd,
            0xee, 0xff,
        ];
        let encoded = encode_crockford(&bytes);
        assert_eq!(encoded.len(), 26);
        assert_eq!(decode_crockford(&encoded).unwrap(), bytes);
    }

    #[test]
    fn crockford_is_case_insensitive_and_handles_ambiguous_chars() {
        let bytes = [0xab; 16];
        let encoded = encode_crockford(&bytes);
        assert_eq!(decode_crockford(&encoded.to_lowercase()).unwrap(), bytes);
        // O/o decode as 0, I/i/L/l decode as 1 — never errors on these.
        assert!(decode_crockford(&encoded.replace('0', "O")).is_ok());
    }

    #[test]
    fn rejects_non_alphabet_chars() {
        assert_eq!(decode_crockford("U").unwrap_err(), IdError::BadDisplayId);
    }
}
