#!/usr/bin/env node
// design-sync build helper for the personal-cfo desktop design system.
//
// The DS (shadcn/ui-style primitives in apps/desktop/src/components) lives INSIDE
// the Vite app — there is no standalone library dist/ and no shipped .d.ts. This
// script produces the two artifacts the converter needs, deterministically:
//
//   1. apps/desktop/.design-sync-entry.tsx — a barrel that `export *`s every DS
//      component file so esbuild lands all exports (primaries + Card*/Table*
//      subcomponents) on window.<global>. Passed to package-build.mjs via --entry.
//
//   2. apps/desktop/.design-sync-dist/ds.css — the app's REAL compiled Tailwind v4
//      stylesheet (tokens + every utility the components use + Inter @font-face),
//      copied out of a `vite build --base ./` with its woff2 siblings so the
//      relative url(./…) refs still resolve. Passed via cfg.cssEntry.
//
// Both outputs are gitignored and regenerated on every sync — run this before
// package-build.mjs / resync.mjs (it is cfg.buildCmd). Idempotent.

import { execFileSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = dirname(dirname(fileURLToPath(import.meta.url)));
const APP = join(REPO, "apps", "desktop");
const SRC = join(APP, "src");

// ── 1. barrel entry ────────────────────────────────────────────────────────
// Every DS component file: src/components/ui/*.tsx plus the top-level
// src/components/*.tsx (PageHeader). Excludes tests/stories. Imports use the
// `@/…` alias so esbuild resolves them via cfg.tsconfig, same as the app.
const isImpl = (f) => /\.tsx$/.test(f) && !/\.(test|stories|spec)\./.test(f);
const files = [
  ...readdirSync(join(SRC, "components", "ui"))
    .filter(isImpl)
    .map((f) => `@/components/ui/${f.replace(/\.tsx$/, "")}`),
  ...readdirSync(join(SRC, "components"))
    .filter((f) => statSync(join(SRC, "components", f)).isFile() && isImpl(f))
    .map((f) => `@/components/${f.replace(/\.tsx$/, "")}`),
].sort();

const barrel = join(APP, ".design-sync-entry.tsx");
writeFileSync(
  barrel,
  "// GENERATED by .design-sync/build.mjs — do not edit; re-run the sync build.\n" +
    "// Barrel re-exporting the design-system components for the design-sync bundle.\n" +
    files.map((m) => `export * from ${JSON.stringify(m)};`).join("\n") +
    "\n",
);
console.error(`barrel: ${relative(REPO, barrel)} (${files.length} modules)`);

// ── 2. compiled CSS + fonts ────────────────────────────────────────────────
// The app's own production build is the most faithful source of the compiled
// Tailwind stylesheet. --base ./ makes asset url()s relative so the font refs
// survive the copy out of dist/.
console.error("vite build --base ./ (apps/desktop)…");
execFileSync("pnpm", ["exec", "vite", "build", "--base", "./"], {
  cwd: APP,
  stdio: "inherit",
  env: { ...process.env, COREPACK_ENABLE_STRICT: "0" },
});

const assets = join(APP, "dist", "assets");
const cssFiles = readdirSync(assets).filter((f) => f.endsWith(".css"));
if (!cssFiles.length) {
  console.error("no CSS emitted by vite build — aborting");
  process.exit(1);
}
// Largest .css is the app stylesheet (utilities + tokens + @font-face).
const css = cssFiles
  .map((f) => [f, statSync(join(assets, f)).size])
  .sort((a, b) => b[1] - a[1])[0][0];

const outDir = join(APP, ".design-sync-dist");
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
cpSync(join(assets, css), join(outDir, "ds.css"));
let fontCount = 0;
for (const f of readdirSync(assets)) {
  if (/\.(woff2?|ttf|otf)$/i.test(f)) {
    cpSync(join(assets, f), join(outDir, basename(f)));
    fontCount++;
  }
}
console.error(
  `css: ${relative(REPO, join(outDir, "ds.css"))} (from ${css}, ${(statSync(join(outDir, "ds.css")).size / 1024).toFixed(0)} KB) + ${fontCount} font file(s)`,
);
