import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `src/bindings.ts` is generated by tauri-specta (personal-cfo-40t) and is the
  // single sanctioned `invoke` call site; it is not hand-edited or linted.
  // `src-tauri/target` is the Rust/Tauri build output (incl. generated codegen
  // assets from `tauri build`); never lint it.
  { ignores: ["dist", "src/bindings.ts", "src-tauri/target"] },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      // TypeScript handles undefined-identifier checking; the lint rule produces
      // false positives on globals (e.g. vitest's describe/it/expect).
      "no-undef": "off",
      // All IPC must flow through the generated typed `commands` wrappers
      // (personal-cfo-40t). Raw `invoke` is allowed only in the generated
      // `src/bindings.ts`, which is excluded from linting above.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@tauri-apps/api/core",
              importNames: ["invoke"],
              message:
                "Do not call invoke() directly — use the typed `commands` from ./bindings (generated by tauri-specta).",
            },
          ],
        },
      ],
    },
  },
  {
    // shadcn/ui primitives co-export a component plus its variant helper (e.g.
    // `buttonVariants`), which is the canonical layout; fast refresh's
    // single-export rule does not apply to these owned design-system files.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  {
    // The vault context module co-locates its provider component with the
    // `useVault` hook and the `describeIpcError` helper — the idiomatic React
    // context layout; fast refresh's single-export rule does not apply.
    files: ["src/vault/useVault.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
);
