//! Per-vault forecast backtest (ADR 0026 §9/§18; bead personal-cfo-nxgx slice 3).
//!
//! "How accurate have this household's *own* past forecasts been?" The daily-on-open
//! persistence (§15) + actualization (§17) already give us historical predicted↔realized
//! pairs: each `forecast_actuals` row links a persisted `forecast_rows` prediction
//! (`amount_p50_minor`) to what actually happened (`realized_amount_minor`). This module
//! aggregates those into a **MAPE** (mean absolute percentage error) over the rows that
//! were actually realized (`exact` / `matched`), writes a `forecast_backtest_results` row,
//! and the readiness "Forecast accuracy" factor reads the latest score.
//!
//! v1 scope: MAPE is taken over every **resolved** prediction — `exact`/`matched` (a real
//! amount landed) *and* `missed` (a predicted event that never happened, scored as a 100%
//! error). Including misses is what makes the metric discriminating: matched rows are within
//! the ±5% link tolerance by construction, so an amount-only MAPE would never leave the
//! envelope — it is the predicted-but-absent events that move the needle. `superseded` rows
//! (stale older-run duplicates) are excluded. A single aggregate across the daily 365-day
//! horizon — not yet bucketed by lead time.

use chrono::NaiveDate;
use rusqlite::{params, OptionalExtension};
use uuid::Uuid;

use crate::DbError;

/// The model the persisted daily runs are generated by (matches the persist tag).
const BACKTEST_MODEL_ID: &str = "layer1_deterministic";
/// The card statement new-charges estimator (ADR 0039 addendum 2026-07-10 §2,
/// personal-cfo-4d8.25.6) — its walk-forward error is tracked as its own metric row.
const CARD_ESTIMATOR_MODEL_ID: &str = "card_statement_estimator_v1";
/// Amount floor (minor units) for the per-row percentage error denominator, so a
/// near-zero prediction can't explode the error.
const BACKTEST_APE_FLOOR_MINOR: i64 = 100;
/// Minimum realized samples before a MAPE is meaningful enough to record / score.
pub(crate) const BACKTEST_MIN_SAMPLE: i64 = 3;

/// Aggregate MAPE (in bps) over realized predictions, plus the sample size. `None` when
/// there are too few realized rows to be meaningful.
pub(crate) fn compute_mape(conn: &rusqlite::Connection) -> Result<Option<(i64, i64)>, DbError> {
    let mut stmt = conn.prepare(
        "SELECT fr.amount_p50_minor, fa.realized_amount_minor
         FROM forecast_actuals fa
         JOIN forecast_rows fr ON fr.id = fa.forecast_row_id
         WHERE fa.match_status IN ('exact', 'matched', 'missed')",
    )?;
    let pairs = stmt
        .query_map([], |r| Ok((r.get::<_, i64>(0)?, r.get::<_, i64>(1)?)))?
        .collect::<Result<Vec<_>, _>>()?;

    if (pairs.len() as i64) < BACKTEST_MIN_SAMPLE {
        return Ok(None);
    }

    // Mean of per-row absolute percentage error, in bps (1% = 100 bps).
    let mut sum_ape_bps = 0i64;
    for (predicted, realized) in &pairs {
        let denom = predicted.abs().max(BACKTEST_APE_FLOOR_MINOR);
        let ape_bps = (realized - predicted).abs() * 10_000 / denom;
        sum_ape_bps += ape_bps;
    }
    let sample = pairs.len() as i64;
    Ok(Some((sum_ape_bps / sample, sample)))
}

/// The card-statement estimator's walk-forward MAPE (in bps) + sample size: predicted vs
/// realized per-window charges over every card's covered history (personal-cfo-4d8.25.6).
/// `None` below [`BACKTEST_MIN_SAMPLE`].
pub(crate) fn compute_card_statement_mape(
    conn: &rusqlite::Connection,
    today: NaiveDate,
) -> Result<Option<(i64, i64)>, DbError> {
    let pairs = crate::forecast::card_statement_walk_forward_pairs(conn, today)?;
    if (pairs.len() as i64) < BACKTEST_MIN_SAMPLE {
        return Ok(None);
    }
    let mut sum_ape_bps = 0i64;
    for (predicted, realized) in &pairs {
        let denom = predicted.abs().max(BACKTEST_APE_FLOOR_MINOR);
        let ape_bps = (realized - predicted).abs() * 10_000 / denom;
        sum_ape_bps += ape_bps;
    }
    let sample = pairs.len() as i64;
    Ok(Some((sum_ape_bps / sample, sample)))
}

/// Compute the per-vault MAPE metrics and append `forecast_backtest_results` rows dated
/// `today` — one for the Layer-1 daily-run accuracy, one for the card-statement estimator's
/// walk-forward error (each skipped below its sample floor). Idempotent per day: an existing
/// row for `(model, today)` is replaced, so repeated opens don't accumulate duplicates.
/// Returns the number of rows written (0..=2).
///
/// # Errors
/// Returns [`DbError`] if a SQLite operation fails.
pub(crate) fn run_backtest(
    conn: &rusqlite::Connection,
    today: NaiveDate,
    horizon_days: u32,
) -> Result<u64, DbError> {
    let mut written = 0;
    if let Some((mape_bps, sample)) = compute_mape(conn)? {
        write_mape_row(
            conn,
            BACKTEST_MODEL_ID,
            today,
            horizon_days,
            mape_bps,
            sample,
        )?;
        written += 1;
    }
    if let Some((mape_bps, sample)) = compute_card_statement_mape(conn, today)? {
        write_mape_row(
            conn,
            CARD_ESTIMATOR_MODEL_ID,
            today,
            horizon_days,
            mape_bps,
            sample,
        )?;
        written += 1;
    }
    Ok(written)
}

/// Append one idempotent `(model, day)` MAPE row.
fn write_mape_row(
    conn: &rusqlite::Connection,
    model_id: &str,
    today: NaiveDate,
    horizon_days: u32,
    mape_bps: i64,
    sample: i64,
) -> Result<(), DbError> {
    // Deterministic id over (model, day) so a second open the same day overwrites rather
    // than appends — the readiness factor only reads the latest anyway.
    let id = Uuid::new_v5(
        &Uuid::NAMESPACE_OID,
        format!("forecast_backtest:{model_id}:{today}").as_bytes(),
    );
    conn.execute(
        "INSERT OR REPLACE INTO forecast_backtest_results
            (id, model_id, as_of_date, horizon_days, metric_type, score_bps,
             sample_size, created_at)
         VALUES (?1, ?2, ?3, ?4, 'mape', ?5, ?6, ?3)",
        params![
            id,
            model_id,
            today.to_string(),
            i64::from(horizon_days),
            mape_bps,
            sample,
        ],
    )?;
    Ok(())
}

/// The most recent recorded Layer-1 MAPE `(score_bps, sample_size)`, if any — the seam the
/// readiness "Forecast accuracy" factor reads. Scoped to [`BACKTEST_MODEL_ID`] so the card
/// estimator's own metric rows (a different model) never masquerade as daily-run accuracy.
///
/// # Errors
/// Returns [`DbError`] if the read fails.
pub(crate) fn latest_mape(conn: &rusqlite::Connection) -> Result<Option<(i64, i64)>, DbError> {
    latest_mape_for(conn, BACKTEST_MODEL_ID)
}

/// The most recent recorded **card-statement-estimator** MAPE `(score_bps, sample_size)`, if any
/// — the walk-forward accuracy of `estimate_card_new_charges`. Sizes the analytic full-payer card
/// lump (personal-cfo-4d8.27.5.7.3). Scoped to [`CARD_ESTIMATOR_MODEL_ID`] (its rows are written
/// daily-on-open alongside the Layer-1 metric); `None` before enough history to record one.
///
/// # Errors
/// Returns [`DbError`] if the read fails.
pub(crate) fn latest_card_statement_mape(
    conn: &rusqlite::Connection,
) -> Result<Option<(i64, i64)>, DbError> {
    latest_mape_for(conn, CARD_ESTIMATOR_MODEL_ID)
}

/// The most recent `(score_bps, sample_size)` MAPE row for one model id.
fn latest_mape_for(
    conn: &rusqlite::Connection,
    model_id: &str,
) -> Result<Option<(i64, i64)>, DbError> {
    let row = conn
        .query_row(
            "SELECT score_bps, sample_size FROM forecast_backtest_results
             WHERE metric_type = 'mape' AND model_id = ?1
             ORDER BY as_of_date DESC, created_at DESC
             LIMIT 1",
            [model_id],
            |r| Ok((r.get::<_, i64>(0)?, r.get::<_, i64>(1)?)),
        )
        .optional()?;
    Ok(row)
}
